{{ if eq $.Values.deployKind "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $.Values.prefix }}drbd-adapter
  labels:
    app: {{ $.Values.prefix }}drbd-adapter
    drbd-version: {{ $.Values.drbdVersion }}
spec:
  selector:
    matchLabels:
      app: {{ $.Values.prefix }}drbd-adapter
  template:
    metadata:
      labels:
        app: {{ $.Values.prefix }}drbd-adapter
        drbd-version: {{ $.Values.drbdVersion }}
    spec:
      initContainers:
      - name: shipper
        image: {{ $.Values.registry }}/drbd9-shipper:{{ $.Values.drbdVersion }}_{{ $.Chart.Version }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs
      {{- $distros := $.Values.distros }}
      {{- if not $distros -}}
        {{- $distros = append $distros "flatcar" }}
        {{- range $index, $node := (lookup "v1" "Node" "" "").items }}
          {{- $osImage := lower $node.status.nodeInfo.osImage }}
          {{- with . -}}
            {{- if regexMatch "(red hat enterprise|centos|almalinux|rocky linux) .*7" $osImage }}
              {{- $distros = append $distros "rhel7" }}
            {{- else if regexMatch "(red hat enterprise|centos|almalinux|rocky linux) .*8" $osImage }}
              {{- $distros = append $distros "rhel8" }}
            {{- else if regexMatch "(red hat enterprise|centos|almalinux|rocky linux) .*9" $osImage }}
              {{- $distros = append $distros "rhel9" }}
            {{- else if regexMatch "ubuntu .*18" $osImage }}
              {{- $distros = append $distros "bionic" }}
            {{- else if regexMatch "ubuntu .*20" $osImage }}
              {{- $distros = append $distros "focal" }}
            {{- else if regexMatch "ubuntu .*22" $osImage }}
              {{- $distros = append $distros "jammy" }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- range $index, $dist := $distros | uniq }}
      {{- if regexMatch "^(rhel[78]|bionic|focal|jammy)$" $dist }}
      {{- $tag := $.Values.drbdVersion  }}
      {{- if eq $dist "jammy" }}
        {{- $tag = "v9.1.11" }}
      {{- end }}
      - name: {{ $dist }}
        image: {{ $.Values.registry }}/drbd9-{{ $dist }}:{{ $tag }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        command: [ /pkgs/entrypoint.adapter.sh ]
        securityContext:
          privileged: true
        env:
        - name: LB_SKIP
          value: 'yes'
        - name: LB_DROP
          value: {{ $.Values.drop | quote }}
        - name: LB_UPGRADE
          value: {{ $.Values.upgrade | quote }}
        - name: LB_CHECK_HOSTNAME
          value: {{ $.Values.checkHostname | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        {{- if regexMatch "^rhel[78]$" $dist }}
        - name: centos-release
          mountPath: /etc/centos-release
          readOnly: true
        {{- end }}
        - name: pkgs
          mountPath: /pkgs
        - name: os-release
          mountPath: /etc/host-release
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-local-bin
          mountPath: /usr-local-bin
        - name: etc-drbd-conf
          mountPath: /etc/drbd.conf
        - name: etc-drbd-d
          mountPath: /etc/drbd.d
        - name: var-lib-drbd
          mountPath: /var/lib/drbd
          readOnly: true
        - name: etc-modules-load
          mountPath: /etc/modules-load.d
        - name: etc-sysconfig-modules
          mountPath: /etc/sysconfig/modules
        {{- end }}
        {{- end }}
      containers:
      - name: monitor
        # Source registry: quay.io/piraeusdatastore/drbd-reactor
        image: {{ $.Values.registry}}/drbd-reactor:{{ $.Values.drbdReactorVersion}}
        imagePullPolicy: {{ $.Values.imagePullPolicy}}
        {{- if regexMatch "^9.1." $.Values.drbdVersion }} # DRBD Reactor only supports DRBD 9.1.x
        command:
        - /usr/sbin/drbd-reactor
        - -c
        - /pkgs/drbd-reactor.toml
        {{- else }}
        command:
        - tail 
        - -f
        - /dev/null     
        {{- end }}  
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs
          readOnly: true
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pkgs
        emptyDir: {}
      - name: os-release
        hostPath:
          path: /etc/os-release
          type: FileOrCreate
      - name: centos-release
        hostPath:
          path: /etc/centos-release
          type: FileOrCreate
      - name: usr-src
        hostPath:
          path: /usr/src    
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-local-bin
        hostPath:
          path: /usr/local/bin
      - name: etc-drbd-conf
        hostPath:
          path: /etc/drbd.conf
          type: FileOrCreate
      - name: etc-drbd-d
        hostPath:
          path: /etc/drbd.d
          type: DirectoryOrCreate
      - name: var-lib-drbd
        hostPath:
          path: /var/lib/drbd
          type: DirectoryOrCreate
      - name: etc-modules-load
        hostPath:
          path: /etc/modules-load.d
          type: DirectoryOrCreate
      - name: etc-sysconfig-modules
        hostPath:
          path: /etc/sysconfig/modules
          type: DirectoryOrCreate   
      affinity:
        nodeAffinity:
		    {{- toYaml $.Values.affinity.nodeAffinity | nindent 10 }}
{{- end }}